name: Github Actions CI TEST

on: push

jobs:
  build_to_dev:
    runs-on: ubuntu-lastest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
